// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go-gqlgen-template/ent"
)

type MutationResponse interface {
	IsMutationResponse()
}

type TodoMutationResponse struct {
	Code    *int      `json:"code"`
	Success *bool     `json:"success"`
	Message *string   `json:"message"`
	Data    *ent.Todo `json:"data"`
}

func (TodoMutationResponse) IsMutationResponse() {}

type UserMutationResponse struct {
	Code    *int      `json:"code"`
	Success *bool     `json:"success"`
	Message *string   `json:"message"`
	Data    *ent.User `json:"data"`
}

func (UserMutationResponse) IsMutationResponse() {}
