// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MutationResponse struct {
	Code    *int        `json:"code"`
	Success *bool       `json:"success"`
	Message *string     `json:"message"`
	Data    interface{} `json:"data"`
}
