// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Street  *string `json:"street"`
	Suite   *string `json:"suite"`
	City    *string `json:"city"`
	Zipcode *string `json:"zipcode"`
	Geo     *Geo    `json:"geo"`
}

type Album struct {
	UserID *int     `json:"userId"`
	ID     *int     `json:"id"`
	Title  *string  `json:"title"`
	Photos []*Photo `json:"photos"`
}

type Comment struct {
	PostID *int    `json:"postId"`
	ID     *int    `json:"id"`
	Name   *string `json:"name"`
	Email  *string `json:"email"`
	Body   *string `json:"body"`
}

type Company struct {
	Name        *string `json:"name"`
	CatchPhrase *string `json:"catchPhrase"`
	Bs          *string `json:"bs"`
}

type Geo struct {
	Lat *string `json:"lat"`
	Lng *string `json:"lng"`
}

type Photo struct {
	AlbumID      *int    `json:"albumId"`
	ID           *int    `json:"id"`
	Title        *string `json:"title"`
	URL          *string `json:"url"`
	ThumbnailURL *string `json:"thumbnailUrl"`
}

type Post struct {
	UserID   *int       `json:"userId"`
	ID       *int       `json:"id"`
	Title    *string    `json:"title"`
	Body     *string    `json:"body"`
	Comments []*Comment `json:"comments"`
}

type Todo struct {
	UserID    *int    `json:"userId"`
	ID        *int    `json:"id"`
	Title     *string `json:"title"`
	Completed *bool   `json:"completed"`
}

type User struct {
	ID       *int     `json:"id"`
	Name     *string  `json:"name"`
	Username *string  `json:"username"`
	Email    *string  `json:"email"`
	Address  *Address `json:"address"`
	Phone    *string  `json:"phone"`
	Website  *string  `json:"website"`
	Company  *Company `json:"company"`
	Todos    []*Todo  `json:"todos"`
	Albums   []*Album `json:"albums"`
}
