// Code generated by ent, DO NOT EDIT.

package ent

import "context"

func (t *Todo) User(ctx context.Context) (*User, error) {
	result, err := t.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = t.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Todo(ctx context.Context) ([]*Todo, error) {
	result, err := u.Edges.TodoOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryTodo().All(ctx)
	}
	return result, err
}
